backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: "Réglages"
    files:
      - file: "data/settings.json"
        label: "Paramètres"
        name: "settings"
        fields:
          - { label: "Titre", name: "title", widget: "string", required: false }
          - { label: "@ admin (sans @)", name: "admin_username", widget: "string", required: false }
          - { label: "@ bot (sans @)", name: "bot_username", widget: "string", required: false }
          - { label: "Texte bouton commande", name: "order_button_label", widget: "string", default: "Commander" }
          - { label: "Nom requis", name: "require_name", widget: "boolean", default: true }
          - { label: "Téléphone requis", name: "require_phone", widget: "boolean", default: true }
          - { label: "Adresse requise", name: "require_address", widget: "boolean", default: true }
          - { label: "Image de fond", name: "theme_bg", widget: "image", required: false }
          - { label: "Opacité voile", name: "theme_overlay_opacity", widget: "number", value_type: "float", min: 0, max: 0.8, step: 0.05, default: 0.4 }
          - { label: "Couleur accent", name: "accent_color", widget: "string", default: "#00e676" }
          - { label: "Logo", name: "header_logo", widget: "image", required: false }

  - name: "products"
    label: "Produits"
    files:
      - file: "data/products.json"
        label: "Liste des produits"
        name: "products"
        fields:
          - label: "Produits"
            name: "items"
            widget: "list"
            summary: "{{fields.title}} — {{fields.price}}€"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Titre", name: "title", widget: "string" }
              - { label: "Prix (€)", name: "price", widget: "number", value_type: "float", min: 0, step: 0.1 }
              - { label: "Badge", name: "badge", widget: "string", required: false }
              - { label: "Image (upload)", name: "image", widget: "image", required: false }
              - { label: "Vidéo (URL)", name: "video", widget: "string", required: false }
              - { label: "Actif", name: "active", widget: "boolean", default: true }
