backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "produits"
    label: "Produits"
    folder: "content/produits"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "title", widget: "string" }
      - { label: "Prix (€)", name: "price", widget: "number" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
