name: Auto build products.json

on:
  push:
    paths:
      - 'content/produits/**'
      - '.github/workflows/auto-products.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate products.json
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = require('path');

          const ROOT = process.cwd();
          const DIR = path.join(ROOT, 'content/produits');

          function walk(dir, out=[]) {
            if (!fs.existsSync(dir)) return out;
            for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
              const p = path.join(dir, entry.name);
              if (entry.isDirectory()) walk(p, out);
              else if (entry.isFile() && p.toLowerCase().endsWith('.md')) {
                out.push(p.replace(ROOT + path.sep, '').replace(/\\/g,'/'));
              }
            }
            return out;
          }

          const files = walk(DIR);
          const repo = process.env.REPO;              // ex: sproduction1313-art/stonr
          const branch = process.env.BRANCH || 'main';
          const urls = files.map(f => `https://raw.githubusercontent.com/${repo}/${branch}/${f}`);

          fs.writeFileSync('products.json', JSON.stringify(urls, null, 2));
          console.log('Generated products.json with', urls.length, 'items');
          NODE

      - name: Commit & push if changed
        run: |
          if git diff --quiet -- products.json; then
            echo "No changes in products.json"
            exit 0
          fi
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add products.json
          git commit -m "Auto-update products.json"
          git push
